# ======================================================================
#  macOS (Apple Silicon) build fix for mvtnorm (Fortran) + Matrix (gettext)
#  - Forces R to use Homebrew's gfortran (gcc) instead of /opt/gfortran
#  - Exposes Homebrew's gettext headers/libs so libintl.h is found
#  - Writes ~/.R/Makevars so future builds inherit correct compilers/flags
#  - Installs mvtnorm and Matrix from source (falls back to binary if needed)
# ======================================================================

message(">>> Checking Homebrew toolchain...")

# Small helper
hb <- function(cmd) suppressWarnings(system(cmd, intern = TRUE))

# Detect Homebrew prefixes
brew_prefix      <- hb("brew --prefix")
gcc_prefix       <- hb("brew --prefix gcc")
gettext_prefix   <- hb("brew --prefix gettext")
if (!nzchar(brew_prefix)) stop("Homebrew not found on PATH. Install Homebrew first: https://brew.sh/")

# Detect gfortran (prefer versioned binary)
gf_candidates <- c(file.path(brew_prefix, "bin", "gfortran-15"),
                   file.path(brew_prefix, "bin", "gfortran-14"),
                   file.path(brew_prefix, "bin", "gfortran"))
gf_bin <- gf_candidates[file.exists(gf_candidates)][1]
if (is.na(gf_bin)) stop("gfortran not found. Run in Terminal: `brew install gcc` and retry.")

# Core include/lib dirs (Apple Silicon Homebrew layout)
inc_dir <- file.path(brew_prefix, "include")  # /opt/homebrew/include
lib_dir <- file.path(brew_prefix, "lib")      # /opt/homebrew/lib

# Sanity check for gettext header
has_libintl <- file.exists(file.path(inc_dir, "libintl.h"))
if (!has_libintl) {
  # Try Cellar path (in case include wasn't linked to /opt/homebrew/include)
  libintl_cellar <- hb("ls /opt/homebrew/Cellar/gettext/*/include/libintl.h")
  if (length(libintl_cellar) && file.exists(libintl_cellar[1])) {
    inc_dir <- dirname(libintl_cellar[1])           # .../Cellar/gettext/<ver>/include
    lib_dir <- sub("/include$", "/lib", inc_dir)    # .../Cellar/gettext/<ver>/lib
  } else {
    stop("gettext header libintl.h not found. Run in Terminal: `brew install gettext` and retry.")
  }
}

message(">>> Using gfortran: ", gf_bin)
message(">>> Using include dir: ", inc_dir)
message(">>> Using lib dir    : ", lib_dir)

# Compose FLIBS (link libs for Homebrew gcc)
if (!nzchar(gcc_prefix)) stop("Homebrew GCC prefix not found. Run: `brew install gcc`.")
flibs <- sprintf("-L%s/lib/gcc/current -lgfortran -lquadmath", gcc_prefix)

# Write ~/.R/Makevars to override the CRAN Framework’s /opt/gfortran settings
mk_dir <- path.expand("~/.R")
mk_file <- file.path(mk_dir, "Makevars")
dir.create(mk_dir, showWarnings = FALSE)

makevars_txt <- sprintf(
  paste(
    "## Auto-generated by mvtnorm+Matrix build fix",
    "## Fortran compilers (Homebrew GCC)",
    "FC  = %s",
    "F77 = %s",
    "F90 = %s",
    "F95 = %s",
    "",
    "## Fortran libs from Homebrew GCC",
    "FLIBS = %s",
    "",
    "## Expose Homebrew headers/libs (gettext, etc.)",
    "CPPFLAGS += -I%s",
    "LDFLAGS  += -L%s",
    "",
    sep = "\n"
  ),
  gf_bin, gf_bin, gf_bin, gf_bin,
  flibs,
  inc_dir, lib_dir
)

writeLines(makevars_txt, mk_file)
message(">>> Wrote ~/.R/Makevars:\n", makevars_txt)

# Session-local env (works even if you don't restart R)
# Also add SDKROOT—R sometimes shows "using SDK: ''" on macOS
sdkroot <- tryCatch(system("xcrun --show-sdk-path", intern = TRUE), error = function(e) "")
old_env <- Sys.getenv(c("FC","F77","F90","F95","CPPFLAGS","LDFLAGS","CPATH","LIBRARY_PATH","PKG_CONFIG_PATH","SDKROOT"), unset = NA)

Sys.setenv(
  FC  = gf_bin, F77 = gf_bin, F90 = gf_bin, F95 = gf_bin,
  CPPFLAGS = paste("-I", inc_dir, sep = ""),
  LDFLAGS  = paste("-L", lib_dir, sep = ""),
  CPATH = inc_dir,
  LIBRARY_PATH = lib_dir,
  PKG_CONFIG_PATH = file.path(gettext_prefix, "lib", "pkgconfig"), # ok if it doesn't exist
  SDKROOT = if (nzchar(sdkroot)) sdkroot else ""
)

# Helper: try install, fall back to binary on failure
install_src_then_binary <- function(pkg) {
  ok <- TRUE
  msg <- NULL
  tryCatch({
    install.packages(pkg, type = "source")
  }, error = function(e) {
    ok <<- FALSE
    msg <<- conditionMessage(e)
  })
  if (!ok) {
    message(sprintf(">>> Source install of %s failed; falling back to CRAN binary. Error:\n%s", pkg, msg))
    options(pkgType = "binary")
    install.packages(pkg)
  } else {
    message(sprintf(">>> %s installed from source.", pkg))
  }
}

message(">>> Installing prerequisites needed by your project (yaml often needed by Rmd) ...")
suppressWarnings(try(install.packages("withr"), silent = TRUE))
suppressWarnings(try(install.packages("yaml"),  silent = TRUE))

message(">>> Installing mvtnorm (Fortran build) ...")
install_src_then_binary("mvtnorm")

message(">>> Installing Matrix (needs libintl.h from gettext) ...")
# First attempt from source
ok <- TRUE; msg <- NULL
tryCatch({
  install.packages("Matrix", type = "source")
}, error = function(e) { ok <<- FALSE; msg <<- conditionMessage(e) })

# If compile still fails, retry with explicit -lintl (rarely needed on macOS)
if (!ok) {
  message(">>> Matrix source build failed; retrying with PKG_LIBS='-lintl' ...")
  old_pkg_libs <- Sys.getenv("PKG_LIBS", unset = "")
  Sys.setenv(PKG_LIBS = paste("-lintl", old_pkg_libs))
  ok2 <- TRUE; msg2 <- NULL
  tryCatch({
    install.packages("Matrix", type = "source")
  }, error = function(e) { ok2 <<- FALSE; msg2 <<- conditionMessage(e) })
  Sys.setenv(PKG_LIBS = old_pkg_libs)
  if (!ok2) {
    message(">>> Matrix still failed from source; falling back to CRAN binary.\n", msg, "\n", msg2)
    options(pkgType = "binary")
    install.packages("Matrix")
  } else {
    message(">>> Matrix installed from source with -lintl.")
  }
} else {
  message(">>> Matrix installed from source.")
}

message(">>> Done. Verifying loaded versions ...")
suppressPackageStartupMessages({
  library(mvtnorm)
  library(Matrix)
})
packageVersion("mvtnorm"); packageVersion("Matrix")

# Replace the broken restore line with this:
restore_env <- function(old_env) {
  # drop any NA names (from unset=NA)
  ok <- !is.na(names(old_env))
  old_env <- old_env[ok]
  # Sys.setenv requires a *named* list
  do.call(Sys.setenv, as.list(old_env))
}

restore_env(old_env)

